---
settings:
  name: Amazon FSx for NetApp ONTAP
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: console-relnotes
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentación de Amazon FSx for NetApp ONTAP
    url: "/index.html"
  - title: Notas de la versión
    url: "/whats-new.html"
  - title: Empezar
    entries:
    - title: Obtenga más información sobre Amazon FSx for NetApp ONTAP
      url: "/start/concept-fsx-aws.html"
    - title: Inicio rápido
      url: "/start/task-getting-started-fsx.html"
    - title: Configurar permisos
      url: "/requirements/task-setting-up-permissions-fsx.html"
    - title: Crear o descubrir un sistema de archivos FSx para ONTAP
      url: "/use/task-create-fsx-system.html"
  - title: Administrar un sistema de archivos FSx para ONTAP
    url: "/use/task-manage-fsx-systems.html"
  - title: Monitorizar operaciones con Tracker
    url: "/use/task-monitor-operations.html"
  - title: Eliminar un sistema de archivos de un proyecto
    url: "/use/task-remove-filesystem.html"
  - title: Eliminar un sistema de archivos FSx para ONTAP
    url: "/use/task-delete-fsx-system.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir asistencia
      url: "/support/task-support-registration.html"
    - title: Obtener ayuda
      url: "/support/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
