= Soporte de respuesta del rastreador
:allow-uri-read: 




=== Soporte de respuesta del rastreador

Tracker ahora proporciona respuestas de API para que puedas ver la salida de la API REST relacionada con la tarea.



=== Compatibilidad con autenticación de enlaces para AWS Secrets Manager

Ahora tiene la opción de usar secretos de AWS Secrets Manager para autenticar enlaces, de modo que no tenga que usar credenciales almacenadas en BlueXP Workloads.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Conéctese a un sistema de archivos FSx para ONTAP con un enlace Lambda"]



=== Implementar las mejores prácticas para un sistema de archivos FSx para ONTAP

BlueXP Workloads proporciona un panel donde puede revisar el estado bien diseñado de las configuraciones de su sistema de archivos.  Puede aprovechar este análisis para implementar las mejores prácticas para sus sistemas de archivos FSx para ONTAP .  El análisis de la configuración del sistema de archivos incluye las siguientes configuraciones: umbral de capacidad SSD, instantáneas locales programadas, FSx programado para copias de seguridad de ONTAP , niveles de datos y replicación de datos remota.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["Obtenga más información sobre el análisis bien diseñado para configuraciones del sistema de archivos"]
* link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_well-architected/improve-configurations.html["Implemente las mejores prácticas para sus sistemas de archivos"]




=== Notificación bien diseñada para problemas del sistema de archivos

En la consola BlueXP , los sistemas de archivos FSx para ONTAP con problemas bien diseñados ahora muestran una notificación en el Canvas que indica cuándo los sistemas de archivos tienen problemas para solucionar.



=== Terminología de permisos actualizada

La interfaz de usuario y la documentación de la fábrica de carga de trabajo ahora usan "solo lectura" para referirse a los permisos de lectura y "lectura/escritura" para referirse a los permisos de automatización.
