---
sidebar: sidebar 
permalink: use/task-manage-fsx-systems.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, bluexp, NetApp Console 
summary: Después de crear o descubrir un sistema FSx para ONTAP en la NetApp Console, puede administrar el sistema de archivos y usar los servicios de datos de NetApp que brindan capacidades como respaldo y recuperación. 
---
= Administrar un sistema de archivos FSx para ONTAP en la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Después de crear o descubrir un sistema FSx para ONTAP en la NetApp Console, puede administrar el sistema de archivos creando volúmenes, administrando máquinas virtuales de almacenamiento, protegiendo datos y administrando el sistema de archivos.  La consola también le permite utilizar servicios de datos que brindan capacidades como copia de seguridad y recuperación, clasificación de datos, sincronización de datos y más.



== Administrar un sistema de archivos mediante cargas de trabajo de NetApp

Cuando abres un sistema FSx para ONTAP desde la página de sistemas de la NetApp Console, vas a NetApp Workloads. Workloads es un servicio inteligente de optimización y automatización que utiliza las mejores prácticas del sector para planificar, aprovisionar y operar cargas de trabajo clave usando Amazon FSx for NetApp ONTAP.

https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["Aprenda a administrar un sistema de archivos mediante NetApp Workloads"^]



== Administrar un sistema de archivos mediante ONTAP System Manager

Puede administrar un sistema de archivos FSx para ONTAP directamente desde la consola utilizando la interfaz del Administrador del sistema ONTAP . Para utilizar System Manager se requiere un agente de consola o un enlace de AWS Lambda.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Aprende a usar los enlaces."^]



== Administrar un sistema de archivos mediante Amazon CloudFormation

Puede aprovisionar y administrar FSx para recursos del sistema de archivos ONTAP (volúmenes, recursos compartidos CIFS, políticas de exportación y más) mediante Amazon CloudFormation.

link:https://github.com/NetApp/NetApp-CloudFormation-FSx-ONTAP-provider["Repositorio de GitHub del proveedor NetApp CloudFormation FSx para ONTAP"^]



== Utilice los servicios de datos de NetApp con un sistema de archivos

Utilice los servicios de datos de NetApp con sus sistemas de archivos FSx for ONTAP para realizar copias de seguridad y recuperar sus datos, transferirlos y sincronizarlos, escanearlos y clasificarlos, replicarlos y acelerar el acceso o descargar el tráfico.



=== Realice copias de seguridad y recupere sus datos

NetApp Backup and Recovery proporciona protección de datos eficiente, segura y rentable para datos, bases de datos y máquinas virtuales de NetApp ONTAP , tanto en las instalaciones como en la nube.

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["Comience a utilizar NetApp Backup and Recovery"^]



=== Transferir y sincronizar datos

NetApp Copy and Sync es un servicio de sincronización y replicación en la nube para transferir datos NAS entre almacenes de objetos locales y en la nube.

link:https://docs.netapp.com/us-en/data-services-copy-sync/task-quick-start.html["Comience a utilizar NetApp Copy and Sync"^]



=== Escanee y clasifique sus datos

NetApp Data Classification le permite escanear y clasificar datos en toda la multicloud híbrida de su organización.

link:https://docs.netapp.com/us-en/data-services-data-classification/index.html["Comience a utilizar la NetApp Data Classification"^]



=== Acelerar el acceso o descargar el tráfico

NetApp Volume Caching proporciona un volumen persistente y escribible en un lugar remoto.  Puede utilizar el almacenamiento en caché de volumen para acelerar el acceso a los datos o para descargar el tráfico de volúmenes con mucho acceso.

link:https://docs.netapp.com/us-en/console-volume-caching/get-started/cache-intro.html["Comience a utilizar NetApp Volume Caching"^]
