---
sidebar: sidebar 
permalink: use/task-replicate-data.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, bluexp, NetApp Console 
summary: Después de crear o descubrir un sistema FSx para ONTAP en la NetApp Console, puede administrar el sistema de archivos y usar los servicios de datos de NetApp que brindan capacidades como respaldo y recuperación. 
---
= Replica datos de FSx for ONTAP en la NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Replica datos para protegerte contra la pérdida de datos si la región donde residen tus datos sufre un desastre. La replicación de datos es compatible entre FSx for ONTAP file systems y sistemas ONTAP locales o Cloud Volumes ONTAP.

.Acerca de esta tarea
Esta operación crea una relación de replicación para volúmenes de origen en un sistema de archivos FSx for ONTAP, un sistema ONTAP local o un sistema Cloud Volumes ONTAP.

Los volúmenes replicados en el sistema de archivos de destino son volúmenes de protección de datos (DP) y siguen el formato de nomenclatura: `{OriginalVolumeName}_copy`.

.Antes de empezar
Tenga en cuenta lo siguiente antes de comenzar.

* Para replicar datos entre FSx for ONTAP y ONTAP local o Cloud Volumes ONTAP, debes seleccionar un agente de Console con conectividad al sistema de archivos o ingresar al sistema de archivos para asociar un enlace. link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Aprende a usar los enlaces."^]
* La replicación no es compatible con volúmenes en un estado distinto de disponible, creado o mal configurado, y cuando la versión de ONTAP no es compatible.


.Pasos
. Desde la página Systems de la consola NetApp, arrastra el sistema de archivos FSx for ONTAP de origen, el sistema ONTAP local o el sistema Cloud Volumes ONTAP sobre el sistema de archivos FSx for ONTAP de destino y selecciona *Replication*.
. En la página Crear replicación, seleccione los volúmenes de origen que desea replicar y luego haga clic en *Siguiente*.
. En Objetivo de replicación, proporcione lo siguiente:
+
.. *Nombre de destino*: aplicaste el nombre de destino cuando arrastraste y soltaste el sistema de almacenamiento de origen en el sistema de destino en la página Console Systems.
.. *Caso de uso*: Seleccione uno de los siguientes casos de uso para la replicación.  Dependiendo del caso de uso seleccionado, Workload Factory completa el formulario con valores recomendados de acuerdo con las mejores prácticas.  Puede aceptar los valores recomendados o realizar cambios a medida que completa el formulario.
+
*** Migración: transfiere sus datos al sistema de archivos FSx de destino para ONTAP
*** Recuperación ante desastres en caliente: garantiza una alta disponibilidad y una rápida recuperación ante desastres para cargas de trabajo críticas
*** Recuperación ante desastres en frío o archivo:
+
**** Recuperación ante desastres en frío: utiliza objetivos de tiempo de recuperación (RTO) y objetos de punto de recuperación (RPO) más largos para reducir costos
**** Archivo: replica datos para almacenamiento a largo plazo y cumplimiento normativo


*** Otro
+
Además, la selección del caso de uso determina la política de replicación, o política de SnapMirror (ONTAP).  Los términos utilizados para describir las políticas de replicación provienen delink:https://docs.netapp.com/us-en/ontap/data-protection/default-protection-policies-concept.html["Documentación de ONTAP 9"^] .

+
**** Para la migración y otros, la política de replicación se llama _MirrorAllSnapshots_.  _MirrorAllSnapshots_ es una política asincrónica para reflejar todas las instantáneas y el último sistema de archivos activo.
**** Para la recuperación ante desastres en caliente, en frío o de archivo, la política de replicación se denomina _MirrorAndVault_.  _MirrorAndVault_ es una política asincrónica y de bóveda para reflejar el último sistema de archivos activo y las instantáneas diarias y semanales.
+
Para todos los casos de uso, si habilita las instantáneas para la retención a largo plazo, la política de replicación predeterminada es _MirrorAndVault_.





.. *Sistema de archivos FSx para ONTAP*: selecciona las credenciales, la región y el nombre del sistema de archivos FSx para ONTAP para el sistema de archivos FSx para ONTAP de destino.
.. *Nombre de la máquina virtual de almacenamiento*: seleccione la máquina virtual de almacenamiento en el menú desplegable.  La máquina virtual de almacenamiento que seleccione es el destino de todos los volúmenes seleccionados en esta relación de replicación.
.. *Nombre del volumen*: El nombre del volumen de destino se genera automáticamente con el siguiente formato `{OriginalVolumeName}_copy` .  Puede utilizar el nombre de volumen generado automáticamente o ingresar otro nombre de volumen.
.. *Política de niveles*: seleccione la política de niveles para los datos almacenados en el volumen de destino.  La política de niveles tiene como valor predeterminado la política de niveles recomendada para el caso de uso que seleccionó.
+
_Equilibrado (automático)_ es la política de niveles predeterminada al crear un volumen mediante la consola de Workload Factory.  Para obtener más información sobre las políticas de niveles de volumen, consultelink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacidad de almacenamiento de volumen"^] en la documentación de AWS FSx para NetApp ONTAP .  Tenga en cuenta que Workload Factory utiliza nombres basados ​​en casos de uso en la consola de Workload Factory para las políticas de niveles e incluye los nombres de políticas de niveles de FSx para ONTAP entre paréntesis.

+
Si seleccionó el caso de uso de migración, Workload Factory selecciona automáticamente copiar la política de niveles del volumen de origen al volumen de destino.  Puede anular la selección para copiar la política de niveles y seleccionar una política de niveles que se aplique al volumen seleccionado para la replicación.

.. *Tasa máxima de transferencia*: seleccione *Limitado* e ingrese el límite máximo de transferencia en MB/s.  Alternativamente, seleccione *Ilimitado*.
+
Sin un límite, el rendimiento de la red y de las aplicaciones puede disminuir.  Como alternativa, recomendamos una velocidad de transferencia ilimitada para los sistemas de archivos FSx para ONTAP para cargas de trabajo críticas, por ejemplo, aquellas que se utilizan principalmente para recuperación ante desastres.



. En Configuración de replicación, proporcione lo siguiente:
+
.. *Intervalo de replicación*: seleccione la frecuencia con la que se transfieren las instantáneas desde el volumen de origen al volumen de destino.
.. *Retención a largo plazo*: de manera opcional, habilite las instantáneas para la retención a largo plazo.  La retención a largo plazo permite que los servicios comerciales sigan funcionando incluso en caso de una falla total del sitio, lo que permite que las aplicaciones conmuten por error de forma transparente mediante una copia secundaria.
+
Las replicaciones sin retención a largo plazo utilizan la política _MirrorAllSnapshots_.  Al habilitar la retención a largo plazo se asigna la política _MirrorAndVault_ a la replicación.

+
Si habilita la retención a largo plazo, seleccione una política existente o cree una nueva para definir las instantáneas que se replicarán y la cantidad que se conservará.

+

NOTE: Para la retención a largo plazo se requieren etiquetas de origen y destino que coincidan.  Si lo desea, Workload Factory puede crear las etiquetas faltantes para usted.

+
*** *Elija una política existente*: seleccione una política existente del menú desplegable.
*** *Crear una nueva política*: ingrese un *nombre de política*.


.. *Instantáneas inmutables*: Opcional.  Seleccione *Habilitar instantáneas inmutables* para evitar que las instantáneas tomadas en esta política se eliminen durante el período de retención.
+
*** Establezca el *Período de retención* en número de horas, días, meses o años.
*** *Políticas de instantáneas*: en la tabla, seleccione la frecuencia de la política de instantáneas y la cantidad de copias que desea conservar.  Puede seleccionar más de una política de instantáneas.


.. *Punto de acceso S3*: opcionalmente, adjunta un punto de acceso S3 para acceder a los datos del sistema de archivos FSx for ONTAP que residen en volúmenes NFS o SMB/CIFS a través de las API de AWS S3. Solo se admite el tipo de acceso a archivos. Proporciona los siguientes detalles:
+
*** *Nombre del punto de acceso S3*: Ingresa el nombre del punto de acceso S3.
*** *Usuario*: selecciona un usuario existente con acceso al volumen o crea un nuevo usuario.
*** *Tipo de usuario*: selecciona *UNIX* o *Windows* como tipo de usuario.
*** *Configuración de red*: selecciona *Internet* o *Virtual private cloud (VPC)*. El tipo de red que elijas determina si el punto de acceso es accesible desde internet o está restringido a una VPC específica.
*** *Habilitar metadatos*: habilitar metadatos crea una tabla de S3 que contiene todos los objetos accesibles por el punto de acceso de S3, que puedes usar para auditoría, gobernanza, automática, análisis y optimización. Habilitar metadatos genera costes adicionales de AWS. Consulta link:https://aws.amazon.com/s3/pricing/["Documentación de precios de Amazon S3"^] para más información.


.. *Etiquetas de punto de acceso S3*: opcionalmente, puedes añadir hasta 50 etiquetas.




. Seleccione *Crear*.

